{#
Copyright (c) 2022-present Snowplow Analytics Ltd. All rights reserved.
This program is licensed to you under the Snowplow Personal and Academic License Version 1.0,
and you may not use this file except in compliance with the Snowplow Personal and Academic License Version 1.0.
You may obtain a copy of the Snowplow Personal and Academic License Version 1.0 at https://docs.snowplow.io/personal-and-academic-license-1.0/
#}

select
    {{ dbt_utils.star(from=ref('snowplow_ecommerce_events'), 
    except=[
            'contexts_com_snowplowanalytics_snowplow_web_page_1_0_0',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_user_1_0_0',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_page_1_0_0',
            'unstruct_event_com_snowplowanalytics_snowplow_ecommerce_snowplo',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_cart_1_0_0',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_product_1_0_0',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_checkout_step',
            'contexts_com_snowplowanalytics_snowplow_ecommerce_transaction_1',
            'contexts_com_snowplowanalytics_snowplow_client_session_1_0_1',
            'contexts_com_snowplowanalytics_mobile_screen_1_0_0'
        ] 
    )}},
    
    null as tr_orderid,
    null as tr_affiliation,
    null as tr_total,
    null as tr_tax,
    null as tr_shipping,
    null as tr_city,
    null as tr_state,
    null as tr_country,
    null as ti_orderid,
    null as ti_sku,
    null as ti_name,
    null as ti_category,
    null as ti_price,
    null as ti_quantity,
    null as pp_xoffset_min,
    null as pp_xoffset_max,
    null as pp_yoffset_min,
    null as pp_yoffset_max,
    null as br_name,
    null as br_family,
    null as br_version,
    null as br_type,
    null as br_renderengine,
    null as br_lang,
    null as br_features_pdf,
    null as br_features_flash,
    null as br_features_java,
    null as br_features_director,
    null as br_features_quicktime,
    null as br_features_realplayer,
    null as br_features_windowsmedia,
    null as br_features_gears,
    null as br_features_silverlight,
    null as br_cookies,
    null as br_colordepth,
    null as br_viewwidth,
    null as br_viewheight,
    null as dvce_type,
    null as dvce_ismobile,
    null as dvce_screenwidth,
    null as dvce_screenheight,
    null as doc_charset,
    null as doc_width,
    null as doc_height,
    null as tr_currency,
    null as tr_total_base,
    null as tr_tax_base,
    null as tr_shipping_base,
    null as ti_currency,
    null as ti_price_base,
    cast(null as {{ type_timestamp() }}) as true_tstamp,
    cast(null as {{ type_timestamp() }}) load_tstamp
    
from {{ ref('snowplow_ecommerce_events') }}
